apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: codefresh-guestbook
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    path: gitops/apps
    repoURL: https://github.com/pnminh/codefresh.git
    targetRevision: gitops
  destination:
    name: in-cluster
    namespace: cf-gitops-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
