apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trio-app-qa
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    path: example-manifests/trio-app/qa
    repoURL: https://github.com/pnminh/promotion-example.git
    targetRevision: main
  destination:
    name: in-cluster
    namespace: demo-ta-qa
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
